# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FindLunch' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FindLunch
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'

  target 'FindLunchTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
